version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
    volumes:
      - modelos:/app/modelos  # Monta el directorio 'modelos' en el contenedor
      - data:/app/data  # Monta el directorio 'data' en el contenedor
    env_file:
      - .env

  
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data


  celery_worker:
    build: .
    command: celery -A app.worker worker --loglevel=info -B
    volumes:
      - .:/app
      - modelos:/app/modelos
    depends_on:
      - redis
      - db
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://user:password@db:5432/mydatabase

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "adminn@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"

volumes:
  postgres_data:
  modelos:
  data:
